version: '3.8'

networks:
  nimax_network:

services:
  backend:
    build: .
    container_name: nimax_backend
    command: > 
      bash -c "sleep 5 &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
    networks:
      - nimax_network
    restart: on-failure
  db:
    image: postgres:15
    container_name: nimax_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - nimax_network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: on-failure

volumes:
  postgres_data:
    name: postgres_data