# Generated by Django 4.2.5 on 2023-09-05 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "price",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(limit_value=1.0)
                        ]
                    ),
                ),
                ("published", models.BooleanField(default=False)),
                ("removed", models.BooleanField(default=False)),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="items", to="categories.category"
                    ),
                ),
            ],
        ),
    ]
